AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  HelloWorldFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: hello-world/app.lambdaHandler
      Runtime: nodejs18.x  # or the selected Node.js runtime
      MemorySize: 128
      Timeout: 3
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /hello
            Method: get